version:            "3.6"
services:
  speedtest:
    container_name: speedtest
    restart: always
    image: adolfintel/speedtest
    volumes:
      - ${DOCKERDIR}/speedtest:/config
    ports:
      - 8888:80
    environment:
      - TZ=${TZ}
  portainer:
    container_name: portainer
    restart: always
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERDIR}/portainer:/data
    ports:
      - 9000:9000
    environment:
      - TZ=${TZ}
